# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='group',
            new_name='groups',
        ),
    ]
