# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0002_auto_20170809_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='groups',
            new_name='assetgroups',
        ),
    ]
