# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0003_auto_20170809_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='configs',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u90e8\u7f72\u7684\u5e94\u7528'),
        ),
    ]
