# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0004_asset_configs'),
    ]

    operations = [
        migrations.CreateModel(
            name='apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=30, verbose_name='\u90e8\u7f72\u7684app')),
                ('ip', models.CharField(max_length=25, verbose_name='\u4e3b\u673aIP')),
                ('status', models.CharField(max_length=20, verbose_name='\u8fd0\u884c\u72b6\u6001')),
            ],
        ),
    ]
