# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0005_apps'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppsHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=25, verbose_name='\u4e3b\u673aIP')),
                ('status', models.CharField(max_length=20, verbose_name='\u8fd0\u884c\u72b6\u6001')),
                ('deploy_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u90e8\u7f72\u8def\u5f84')),
            ],
        ),
        migrations.RenameField(
            model_name='apps',
            old_name='app',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='ip',
        ),
        migrations.AddField(
            model_name='apps',
            name='apphosts',
            field=models.ManyToManyField(blank=True, to='nova.AppsHost', verbose_name='\u90e8\u7f72\u7684ip'),
        ),
    ]
