# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0007_auto_20170817_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='appshost',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
