# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0008_auto_20170817_1103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppsHost',
            new_name='AppHost',
        ),
    ]
