# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0009_auto_20170817_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='apphost',
            name='name',
            field=models.CharField(default=2, max_length=25, verbose_name='\u5e94\u7528\u540d\u79f0'),
            preserve_default=False,
        ),
    ]
