# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0010_apphost_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='port',
            field=models.IntegerField(default=3300, verbose_name='\u5e94\u7528\u7aef\u53e3\u53f7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apphost',
            name='port',
            field=models.IntegerField(default=3300, verbose_name='\u5e94\u7528\u7aef\u53e3\u53f7'),
            preserve_default=False,
        ),
    ]
