# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0011_auto_20170818_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='apphosts',
            field=models.ManyToManyField(blank=True, to='nova.AppHost', verbose_name='\u670d\u52a1\u8282\u70b9\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u670d\u52a1\u540d\u79f0'),
        ),
    ]
