# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0012_auto_20170818_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(max_length=50, verbose_name='\u4e3b\u673a\u540d'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ip',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='\u4e3b\u673aIP'),
        ),
    ]
