# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0013_auto_20170822_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, verbose_name='\u4efb\u52a1id')),
                ('name', models.CharField(max_length=20, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('status', models.CharField(max_length=20, verbose_name='\u8fd0\u884c\u72b6\u6001')),
                ('result', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u7ed3\u679c')),
            ],
        ),
    ]
