# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0014_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=80, verbose_name='\u4efb\u52a1\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=40, verbose_name='\u8fd0\u884c\u72b6\u6001'),
        ),
    ]
