# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0018_app_svn_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='svn_url',
            field=models.TextField(blank=True, null=True, verbose_name='SVN\u8def\u5f84'),
        ),
    ]
