# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0019_task_svn_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='app',
            name='env',
            field=models.CharField(default='test', max_length=25, verbose_name='\u90e8\u7f72\u73af\u5883'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apphost',
            name='env',
            field=models.CharField(default='test', max_length=25, verbose_name='\u90e8\u7f72\u73af\u5883'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='env',
            field=models.IntegerField(blank=True, choices=[(1, '\u751f\u4ea7\u73af\u5883'), (2, '\u51c6\u751f\u4ea7\u73af\u5883'), (3, '\u6d4b\u8bd5\u73af\u5883')], null=True, verbose_name='\u8fd0\u884c\u73af\u5883'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
