# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-21 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0020_auto_20170919_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4efb\u52a1\u8be6\u60c5'),
        ),
    ]
