# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0021_task_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u670d\u52a1\u540d\u79f0')),
                ('svn_url', models.CharField(max_length=150, null=True, verbose_name='SVN\u8def\u5f84')),
                ('files', models.CharField(max_length=30, verbose_name='\u914d\u7f6e\u6587\u4ef6')),
                ('env', models.CharField(max_length=25, verbose_name='\u90e8\u7f72\u73af\u5883')),
            ],
        ),
    ]
