# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0022_appconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='files',
            field=models.CharField(max_length=100, verbose_name='\u914d\u7f6e\u6587\u4ef6'),
        ),
    ]
