# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-30 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0024_auto_20170930_1547'),
        ('nova', '0024_auto_20170929_1912'),
    ]

    operations = [
    ]
