# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0025_merge_20170930_1737'),
        ('nova', '0026_assetgroup_asset_groups'),
    ]

    operations = [
    ]
