# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-10 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0026_assetgroup_asset_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='execute_user',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u64cd\u4f5c\u4eba'),
        ),
    ]
