# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-10 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0027_task_execute_user'),
        ('nova', '0027_merge_20171009_1116'),
    ]

    operations = [
    ]
