# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-11 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0028_merge_20171010_1008'),
        ('nova', '0028_auto_20171011_1125'),
    ]

    operations = [
    ]
