# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-09 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0029_merge_20171011_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u6570\u636e\u5e93')),
                ('env', models.CharField(max_length=20, verbose_name='\u73af\u5883')),
                ('sql', models.TextField(blank=True, null=True, verbose_name='sql')),
                ('start_time', models.DateTimeField(verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('result', models.CharField(blank=True, max_length=2000, null=True, verbose_name='\u7ed3\u679c')),
                ('execute_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u64cd\u4f5c\u4eba')),
            ],
        ),
    ]
