# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-10 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0032_auto_20171110_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='sql',
            name='recovery_file',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='\u6062\u590d\u6587\u4ef6'),
        ),
    ]
