# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-10 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0033_sql_recovery_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(blank=True, max_length=30, verbose_name='Access KEY')),
                ('access_sec', models.CharField(max_length=30, verbose_name='Access Secret')),
                ('env', models.CharField(max_length=20, verbose_name='\u73af\u5883')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=30, verbose_name='\u6587\u4ef6\u540d\u79f0')),
                ('file_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6587\u4ef6\u8def\u5f84')),
                ('env', models.CharField(max_length=20, verbose_name='\u73af\u5883')),
                ('oss_name', models.CharField(max_length=30, verbose_name='oss\u540d\u79f0')),
                ('upload_time', models.DateTimeField(verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('result', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7ed3\u679c')),
            ],
        ),
    ]
