# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-10 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0034_accesskey_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='ip',
            field=models.CharField(max_length=80, verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='database',
            name='password',
            field=models.CharField(max_length=40, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='database',
            name='username',
            field=models.CharField(max_length=30, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
