# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-14 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0036_auto_20171111_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6587\u4ef6\u7c7b\u578b'),
        ),
    ]
