# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-22 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0038_database_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='comment',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u8bf4\u660e'),
        ),
    ]
