# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-30 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0039_database_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesskey',
            name='access_key',
        ),
        migrations.RemoveField(
            model_name='accesskey',
            name='access_sec',
        ),
        migrations.AddField(
            model_name='accesskey',
            name='accessKeyID',
            field=models.CharField(default='ssss', max_length=30, verbose_name='AccessKEY ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesskey',
            name='accessKeySecret',
            field=models.CharField(default=555, max_length=200, verbose_name='AccessKEY Secret'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesskey',
            name='cname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OSS Bucket Cname'),
        ),
        migrations.AddField(
            model_name='accesskey',
            name='ossBucketName',
            field=models.CharField(default=1, max_length=64, verbose_name='OSS Bucket Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='oss_name',
            field=models.CharField(max_length=64, verbose_name='oss\u540d\u79f0'),
        ),
    ]
