# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-30 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0040_auto_20171130_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='app',
            field=models.ManyToManyField(blank=True, to='nova.App', verbose_name='\u5e94\u7528\u540d\u79f0'),
        ),
    ]
