# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-30 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0041_accesskey_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='OssBucketApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u5e94\u7528\u540d\u79f0')),
                ('env', models.CharField(max_length=20, verbose_name='\u73af\u5883')),
                ('ossBucketName', models.CharField(max_length=64, verbose_name='OSS Bucket Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='accesskey',
            name='app',
        ),
        migrations.AddField(
            model_name='accesskey',
            name='ossBucketApp',
            field=models.ManyToManyField(blank=True, to='nova.OssBucketApp', verbose_name='bucket\u5e94\u7528\u540d\u79f0'),
        ),
    ]
