# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-30 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0042_auto_20171130_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='oss_name',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='app_name',
            field=models.CharField(default=1, max_length=64, verbose_name='\u5e94\u7528\u540d\u79f0'),
            preserve_default=False,
        ),
    ]
