# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-01 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0043_auto_20171130_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ossbucketapp',
            name='ossBucketName',
        ),
        migrations.AddField(
            model_name='ossbucketapp',
            name='comment',
            field=models.CharField(default='test', max_length=64, verbose_name='\u8bf4\u660e'),
            preserve_default=False,
        ),
    ]
