# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-05 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0046_auto_20171205_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='app_name',
        ),
        migrations.AddField(
            model_name='task',
            name='app_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='app_id'),
        ),
    ]
