# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-14 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0050_auto_20171214_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpstep',
            name='required_item',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8fd4\u56de\u9879'),
        ),
        migrations.AlterField(
            model_name='httpstep',
            name='required',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8fd4\u56de\u503c'),
        ),
    ]
