# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-14 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0051_auto_20171214_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u670d\u52a1\u540d\u79f0')),
                ('status', models.CharField(max_length=100, verbose_name='\u72b6\u6001')),
                ('last_check_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4e0a\u6b21\u68c0\u67e5\u65f6\u95f4')),
                ('next_check_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4e0b\u6b21\u68c0\u67e5\u65f6\u95f4')),
            ],
        ),
    ]
