# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-14 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0052_httptest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httptest',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u670d\u52a1\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='httptest',
            name='status',
            field=models.IntegerField(max_length=10, verbose_name='\u72b6\u6001'),
        ),
    ]
