# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-14 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0053_auto_20171214_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='httptest',
            name='comment',
            field=models.CharField(default=111, max_length=50, verbose_name='\u8bf4\u660e'),
            preserve_default=False,
        ),
    ]
