# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-14 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0054_httptest_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httptest',
            name='status',
            field=models.IntegerField(verbose_name='\u72b6\u6001'),
        ),
    ]
