# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-14 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0056_auto_20171214_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='httpstep',
            old_name='itemid',
            new_name='history',
        ),
    ]
