# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-14 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0058_auto_20171214_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='itemid',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='itemid'),
        ),
    ]
