# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-15 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0059_auto_20171214_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('token', models.CharField(max_length=100, verbose_name='token')),
                ('last_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u83b7\u53d6token\u65f6\u95f4')),
                ('comment', models.CharField(max_length=80, verbose_name='\u8bf4\u660e')),
            ],
        ),
    ]
