# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-15 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0060_httptoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httptoken',
            name='last_time',
            field=models.BigIntegerField(default=1, verbose_name='\u83b7\u53d6token\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
