# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-19 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0062_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='itemid',
        ),
        migrations.RemoveField(
            model_name='httpstep',
            name='history',
        ),
        migrations.AddField(
            model_name='history',
            name='item_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='item_id'),
        ),
        migrations.AddField(
            model_name='httpstep',
            name='item_id',
            field=models.CharField(default=0, max_length=20, verbose_name='item_id'),
            preserve_default=False,
        ),
    ]
