# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-19 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0063_auto_20171219_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='httptest',
            name='item_id',
            field=models.CharField(default=0, max_length=20, verbose_name='item_id'),
            preserve_default=False,
        ),
    ]
