# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-19 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0064_httptest_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httptest',
            name='comment',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='httptest',
            name='status',
            field=models.IntegerField(blank=True, verbose_name='\u72b6\u6001'),
        ),
    ]
