# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-19 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0065_auto_20171219_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpstep',
            name='item_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='item_id'),
        ),
    ]
