# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-10 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0066_auto_20171219_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('config_key', models.CharField(blank=True, max_length=80, null=True, verbose_name='\u914d\u7f6e\u53c2\u6570')),
                ('config_value', models.CharField(blank=True, max_length=2000, null=True, verbose_name='\u914d\u7f6e\u53c2\u6570\u503c')),
                ('comment', models.BigIntegerField(blank=True, null=True, verbose_name='\u8bf4\u660e')),
            ],
        ),
    ]
