# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-16 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0069_auto_20180112_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='areceiver',
            new_name='receiver',
        ),
    ]
