# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-24 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0073_servicehistory_servicestep_servicetest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceHistory',
        ),
    ]
