# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-24 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0074_delete_servicehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetest',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u8bf4\u660e'),
        ),
    ]
