# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-24 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0075_auto_20180124_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestep',
            name='db_env',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6570\u636e\u5e93\u73af\u5883'),
        ),
        migrations.AddField(
            model_name='servicestep',
            name='db_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6570\u636e\u5e93\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='servicestep',
            name='status_codes',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u8fd4\u56de\u72b6\u6001\u7801'),
        ),
        migrations.AlterField(
            model_name='servicestep',
            name='step_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u8bf7\u6c42\u7c7b\u578b'),
        ),
    ]
