# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-13 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0077_operationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('access_asset', '\u8d44\u4ea7\u7ba1\u7406'), ('access_app', '\u7cfb\u7edf\u7ba1\u7406'), ('access_database', '\u6570\u636e\u5e93\u7ba1\u7406'), ('access_monitor', '\u76d1\u63a7\u7ba1\u7406'), ('access_task', '\u4efb\u52a1\u7ba1\u7406'), ('access_file', '\u6587\u4ef6\u7ba1\u7406'), ('access_log', '\u65e5\u5fd7\u7ba1\u7406')),
            },
        ),
    ]
