# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-16 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0083_auto_20180316_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetgroup',
            old_name='asset_groups',
            new_name='user_groups',
        ),
    ]
