# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-16 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0085_auto_20180316_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='appgroups',
            new_name='app_groups',
        ),
    ]
