# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-16 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0086_auto_20180316_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='apphosts',
        ),
        migrations.AddField(
            model_name='app',
            name='app_hosts',
            field=models.ManyToManyField(blank=True, to='nova.AppHost', verbose_name='\u5e94\u7528\u90e8\u7f72\u7684\u670d\u52a1\u5668'),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u5e94\u7528\u540d\u79f0'),
        ),
    ]
