# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-16 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0087_auto_20180316_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='assetgroups',
            new_name='asset_groups',
        ),
    ]
