# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-12 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0092_auto_20180402_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='connect_method',
            field=models.CharField(choices=[(b'Password', '\u5bc6\u7801\u8fde\u63a5'), (b'PublicKey', '\u516c\u94a5\u8fde\u63a5')], default='PublicKey', max_length=30, verbose_name='\u8fde\u63a5\u65b9\u5f0f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='public_key_file',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u79c1\u94a5\u6587\u4ef6'),
        ),
    ]
