# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-16 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0093_auto_20180412_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='env',
            field=models.CharField(blank=True, choices=[(b'product', '\u751f\u4ea7\u73af\u5883'), (b'staging', '\u51c6\u751f\u4ea7\u73af\u5883'), (b'uat', '\u7528\u6237\u6d4b\u8bd5\u73af\u5883'), (b'test', '\u6d4b\u8bd5\u73af\u5883'), (b'dev', '\u5f00\u53d1\u73af\u5883')], max_length=25, null=True, verbose_name='\u8fd0\u884c\u73af\u5883'),
        ),
    ]
