# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-17 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0094_auto_20180516_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=40, verbose_name='\u5e94\u7528\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='apphost',
            name='name',
            field=models.CharField(max_length=40, verbose_name='\u5e94\u7528\u540d\u79f0'),
        ),
    ]
