# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-17 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0097_jdkbuildversion_jdk_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jdkbuildversion',
            name='app_name',
            field=models.CharField(max_length=40, verbose_name='\u5e94\u7528\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='jdkbuildversion',
            name='env',
            field=models.CharField(max_length=40, verbose_name='\u5e94\u7528\u90e8\u7f72\u73af\u5883'),
        ),
        migrations.AlterField(
            model_name='jdkbuildversion',
            name='jdk_path',
            field=models.CharField(max_length=80, verbose_name='jdk\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='jdkbuildversion',
            name='jdk_version',
            field=models.CharField(max_length=20, verbose_name='JDK\u7248\u672c'),
        ),
    ]
